### ISSUE TITLE
Add keyboard shortcuts for the plus button and opening containers

### ISSUE THREAD

**Issue by TanviHacks** [mozilla/testpilot-containers#119]
Can we define keyboard shortcuts for the plus button and for opening containers?

Ideas on what these should be are welcome here.

**Comment by TanviHacks** [comment]
@johngruen @groovecoder @jonathanKingston @kjozwiak - suggestions?

**Comment by TanviHacks** [comment]
@bakulf

**Comment by jonathanKingston** [comment]
I will add the long press plus button keyboard shortcut now.

**Comment by groovecoder** [comment]
Adding a 👍 based on a Discourse request for this.

**Comment by mikejarema** [comment]
For clarity -- @TanviHacks when you say "Can we define keyboard shortcuts for ... opening containers?" do you specifically mean keyboard shortcuts for _opening a new container tab_?

I'm a very heavy container user, and on my Mac I've defined some custom shortcuts which work (albeit unreliably, as the menu bar needs focus and even then sometime they fail).

As a concrete example, I use ⌥⌘1 through ⌥⌘4 to open new container tabs... it's great when it works:

![screen shot 2017-03-02 at 4 44 01 pm](https://cloud.githubusercontent.com/assets/373798/23528334/7f9d1ca4-ff67-11e6-9ccd-47558002f349.jpg)

**Comment by ChenMorpheus** [comment]
It would be perfect to have keyboard shortcuts for creating containers, and we can just make it like what @mikejarema did as long as we can ensure it will not conflict with other keyboard shortcuts. What do you think?

**Comment by jnachtigall** [comment]
FWIW, there's also #338 for having shortcuts to hiding/showing containers (toggle). I guess "opening" and "hiding/showing" shortcuts should fit each other for easy memorization.

**Comment by biva** [comment]
Other way of using shortcuts: today I can open a link in a new tab with Ctrl + left click. I'd love to open a link in a new tab choosing the container this way (for example):
- Middle button: same container
- Ctrl + left click: Container 1
- Shift + left click: Container 2
- Alt + left click: No container
- Ctrl + Alt + left click: Container 3

In addition, if I use the right click instead of the left click, it doesn't open the "right click menu", but it opens the link in the same tab (no new tab):
- Ctrl + right click: Container 1 in the same tab (no new tab)
- Shift + right click: Container 2 in the same tab (no new tab)
- ...

And different behavior with the middle button:
- Ctrl + middle click: new tab Container 4
- Shift + middle click: new tab Container 5
- ...

The best would be that these shortcuts can be configurable by the user, with all possible combination of Ctrl, Alt, Shift, left click, middle click and right click! :)

**Comment by kjozwiak** [comment]
Just for reference, there was some discussions in the past about adding keyboard shortcuts in [bug#1245262](https://bugzilla.mozilla.org/show_bug.cgi?id=1245262) which ended up being a lot more difficult due to finding a consistent experience across platforms.

**Comment by jonathanKingston** [comment]
This was solved by my latest patch with Ctrl+Y however there is some issues making this a little unusable currently.

Namely both:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1325697
- https://bugzilla.mozilla.org/show_bug.cgi?id=1365222

Feel free to reopen etc if there is still need here.

**Comment by erfanio** [comment]
@jonathanKingston Ctrl+Y doesn't really solve the problem of opening a container with keyboard shortcut since it still requires mouse action (no way to navigate the menu with keyboard).
Even something like Ctrl+Y+1 ... Ctrl+Y+0 would be good enough for now. But just a shortcut to open the menu... I don't really see it as that useful (since you still need to move the mouse to it)

**Comment by groovecoder** [comment]
You can navigate the pop-up menu with <tab> and <shift+tab>

**Comment by erfanio** [comment]
Ah that's cool................. Wait a second
I have two containers and this is the focus order:

1. First container
2. Reorder tab button
3. The entire popup (??)
4. New container button
5. Edit container button
6. Second container

I call this unusable!

**Comment by jonathanKingston** [comment]
I'm going to propose we use Ctrl+Comma as commands that relate to text fields impact the location bar and make them pretty hard to use: https://bugzilla.mozilla.org/show_bug.cgi?id=1325697

Will have raised bug #546, the required tabbing will still be an issue.

**Comment by comzeradd** [comment]
> This was solved by my latest patch with Ctrl+Y however there is some issues making this a little unusable currently.

Is this solved for all OS versions? I'm currently on Nightly on Linux and I don't see any shortcuts for my tab containers.

**Comment by jonathanKingston** [comment]
We moved this to Ctrl+. (Period) as it didn't work on all operating systems.

**Comment by akien-mga** [comment]
> We moved this to Ctrl+. (Period) as it didn't work on all operating systems.

Did it change again? Neither Ctrl+. nor Ctrl+Y work for me with the current Nightly on Windows 7.

**Comment by biva** [comment]
Hello,

Could you reopen this issue? Neither Ctrl+. nor Ctrl+Y work for me (Windows 10, FF 56, Container v4.0.3). Could you also consider a key that is accessible with only the left hand (Ctrl+T is possible, Ctrl+. is much harder). Could you also consider internationl keyboards? (for example French doesn't have the same layout).

In addition, it would be great to have more keyboard shortcuts, especially in order to solve this issue: https://github.com/mozilla/multi-account-containers/issues/914 (and be able to open a link in a new default-container-tab without to much steps). These keyboards should also work with bookmarks (see https://github.com/mozilla/multi-account-containers/issues/323)

Maybe related to https://github.com/mozilla/multi-account-containers/issues/823

**Comment by marco-c** [comment]
@jonathanKingston what is the new keyboard shortcut?

**Comment by inwardmovement** [comment]
`Ctrl + .` doesn't work with a french keyboard on Firefox Developer Edition

**Comment by almet** [comment]
I concur. I wonder if this is a more profound problem, which happens on other keyboard layouts. If I pass my layout in english, I can use the shortcut, but with a french layout it doesn't seem to work. @jonathanKingston any idea about what's going on?

**Comment by rtimmons** [comment]
Can this issue be re-opened?

Control+. on a mac opens the container menu from the toolbar, but it doesn't seem possible to use the keyboard to select a container. The mouse is still required.

**Comment by jnachtigall** [comment]
@rtimmons I agree that the current workflow is not the best, especially with regards to discoverability. 

But you can select a container without the mouse by using `<Ctrl>+.` and then `<Tab>` (forth) or `<Shift>+<Tab>` (backwards) and then `<Enter>` to select a new Container.

**Comment by groovecoder** [comment]
👍 @jnachtigall - you should be able to use `<Tab>` and `<Shift>+<Tab>` and `<Enter>` to open a tab in a selected container.

**Comment by JalilArfaoui** [comment]
`Ctrl + .` doesn't work with a french keyboard (Linux / Gnome / Firefox 59.0.2)

**Comment by remeh** [comment]
Same problem here with a french keyboard. This feature is great and useful but loses a lot of sense with the keyboard shortcut not working. (Linux / Xfce / Firefox 59.0.2)

**Comment by Guillaumebeuzeboc** [comment]
Doesn't work on ubuntu16.04/firefox 60.0.1 with qwerty keyboard

**Comment by dns2utf8** [comment]
I like `Ctrl + .` on Linux but it should be documented and advertised. I found this bug only after somebody pointed me at it.

**Comment by fdorantesm** [comment]
I don't have shortcuts option in MacOS.
![imagen](https://user-images.githubusercontent.com/19377556/84848106-2c783300-b018-11ea-94d1-fe423de25874.png)

**Comment by Flimm** [comment]
In newer versions of Firefox Mult-Account Containers, you can use these keyboard shortcuts:

- <kbd>ctrl</kbd>-<kbd>shift</kbd>-<kbd>1</kbd> to open a new tab with the first container
- <kbd>ctrl</kbd>-<kbd>shift</kbd>-<kbd>2</kbd> to open a new tab with the second container
- and so on
- <kbd>ctrl</kbd>-<kbd>.</kbd> to open the container menu

On macOS, replace <kbd>ctrl</kbd> with <kbd>command</kbd>.

See this superuser.com answer: https://superuser.com/q/1396464/90668
